### ISSUE TITLE
I want to translate this mod from English into Chinese

### ISSUE THREAD

**Issue by YPXxiao** [e99999/GT-Classic#127]
And can you give me permission to repost your mod to MCBBS（www.mcbbs.net）？

**Comment by Rongmario** [comment]
可以先 PR 翻譯的 .lang 在這嗎？

**Comment by YPXxiao** [comment]
> 可以先 PR 翻譯的 .lang 在這嗎？

https://www.mcbbs.net/thread-968064-1-1.html

The translation will probably take a while...

**Comment by e99999** [comment]
closing this and you can post any messages to me in your other issue or in our discord https://discord.gg/RgfNjXF
