### ISSUE TITLE
zh_cn.lang of GregTech Classic

### ISSUE THREAD

**Issue by YPXxiao** [e99999/GT-Classic#128]
https://github.com/YPXxiao/YPXxiao-Repository/

**Comment by YPXxiao** [comment]
@Rongmario @e99999

**Comment by CrossVas** [comment]
Just make a fork of this repository, create a new .lang file, write the translation an then make a pull request.

**Comment by e99999** [comment]
Yeah as CrossVas said, fork the repo and just PR your fork with the added lang file when you finish. @YPXxiao

**Comment by CrossVas** [comment]
And after [line 9](https://github.com/YPXxiao/YPXxiao-Repository/blob/91ae511f5d9945d874c8ff2985a517295305f53c/zh_cn.lang#L9) you should have:
tile.gtclassic.blockPlatinum.name=Block of Platinum

**Comment by e99999** [comment]
Ok ive added what you got so far into GTC to be in the next release (1.1.2), youll need to update it as your missing some stuff. Feel free to make changes and let me know when your ready for me to copy it over again.

**Comment by e99999** [comment]
stale, added what i could but needs to be updated
