### ISSUE TITLE
Strange crash w/ ae2 when starting a server

### ISSUE THREAD

**Issue by frank89722** [e99999/GT-Classic#131]
I'm trying to update GTC to 1.1.3 in my modpack.
It works fine on client side but it crashed on server with ae2

crash report: https://pastebin.com/mxgVNLV9
log: [latest.log](https://github.com/e99999/GT-Classic/files/4398424/latest.log)

Please let me know if this should be reported to ae2

**Comment by e99999** [comment]
ah ok, its a small mistake by that is a compounded by whatever ASM is happening there. Fixed - will be in the release this Friday.
