### ISSUE TITLE
Testing Player Detector Block

### ISSUE THREAD

**Issue by CrossVas** [e99999/GT-Classic#134]
After couple of tests I did with Player Detector, I found that: 
PD = Player Detector;
1. PD + Redstone = Okay, it works as intended. 
2. PD + Solid Block:
 - If you place a solid block next to PD when it is active, solid block will receive a constant redstone signal even when the player is far;
 - If you place a solid block next to PD when it is not active, solid block will not receive redstone signal at all.   
3. PD + Door next to it (all directions) = game crash when you go away from PD ([crash-report](https://hastebin.com/gudoreduwu.php))

- https://imgur.com/u57IwAO

- https://imgur.com/UH9Gz9C
- https://imgur.com/8Sbuk3m

![2020-04-26_15 37 14](https://user-images.githubusercontent.com/25727222/80308035-5c077d80-87d5-11ea-8017-f0b1e2b140df.png)

![2020-04-26_15 34 25](https://user-images.githubusercontent.com/25727222/80308040-63c72200-87d5-11ea-8328-0548c219cf0a.png)

**Comment by e99999** [comment]
fixed crash, working on block update issue 👍

**Comment by e99999** [comment]
fixed, will be in next release (1.15)
