### ISSUE TITLE
Recipe iterator creates recipes without checks, causing duplication glitch

### ISSUE THREAD

**Issue by YuRaNnNzZZ** [e99999/GT-Classic#135]
AE2 registers quartz dust, GTC thinks it's okay to add quartz block to 9 quartz dust recipe in macerator (dustPrismarine is registered without AE2 but it's the same issue)
![javaw_2020-05-03_14-52-27](https://user-images.githubusercontent.com/5104603/80913572-3b4ba480-8d4e-11ea-97c5-bfd67dd41b2e.png)

Except that it's crafted from 4 quartz, not 9:
![javaw_2020-05-03_14-52-31](https://user-images.githubusercontent.com/5104603/80913592-67ffbc00-8d4e-11ea-940e-ca7510e7afef.png)

IC2C 1.12-1.5.4.5, GTC 1.1.5 (4c396ea)

**Comment by e99999** [comment]
fixed in next release 👌
