### ISSUE TITLE
OverLoaded LootTables

### ISSUE THREAD

**Issue by sscards55** [e99999/GT-Classic#158]
Currently the way GTC adds loot to chest is to add it to the main pool of loot generated, could you instead add a new pool so that GTC loot is not the only thing being generated?

**Comment by e99999** [comment]
i would suggest disabling gtc loot entirely in the config and modify tables yourself for custom needs.

**Comment by sscards55** [comment]
I've done that already, it's just really annoying that it has to be done this way. It would be really nice if GTC loot wasn't the only thing that shows up in a lootchest.
