### ISSUE TITLE
Custom industrial centrifuge recipe not using the right amount of resources.

### ISSUE THREAD

**Issue by impactwinter** [e99999/GT-Classic#159]
I made a custom recipe for the industrial centrifuge using CraftTweaker but it doesn't use the right amount of nitre/saltpeter. It should be using 9 but it only uses 1

Here's the one line of ZenScript:

`IndustrialCentrifuge.addCellRecipe([<gtclassic:test_tube>.withTag({Fluid: {FluidName: "oxygen", Amount: 1000}}) * 3, <gtclassic:test_tube>.withTag({Fluid: {FluidName: "nitrogen", Amount: 1000}}), <gtclassic:test_tube>.withTag({Fluid: {FluidName: "potassium", Amount: 1000}})], <ore:dustNiter> * 9, 5, 32000);`

I'm using the most recent version of GT-Classic (1.1.6) 

![2021-01-09_21 47 38](https://user-images.githubusercontent.com/47050672/104113147-b9405200-52c4-11eb-9134-062b2ad7b45d.png)

**Comment by Trinsdar** [comment]
Yah it's a known issue with our crafttweaker compat, if the input ingredient is an oredict with more then one entry in the oredict, then in jei it will only show requireing an amount of 1, the recipe itself though still requiresthe correct amount. We are don't really have any idea how to fix the issue, it seems to be in other mods that add crafttweaker support for both ic2 classic and experimental, so ic2 tweaker for example.

**Comment by impactwinter** [comment]
alrigh, thanks
