### ISSUE TITLE
quantum chest no display all content with logistical pipe

### ISSUE THREAD

**Issue by louino2478** [e99999/GT-Classic#161]
I made a tiny logistics pipes network with quantum chest for the storage
![2021-07-08_10 18 30](https://user-images.githubusercontent.com/50880693/124891801-9a075080-dfd9-11eb-969b-844bf538d43b.png)
![2021-07-08_10 18 56](https://user-images.githubusercontent.com/50880693/124892040-cae78580-dfd9-11eb-9250-64896aa5c6ee.png)
in my quantum  chest, there are coblestone.
![2021-07-08_10 18 53](https://user-images.githubusercontent.com/50880693/124892264-03875f00-dfda-11eb-829d-f68adc4cb67b.png)
but, logistics pipes display only 64 coblestone. i can push coblestone in network and store on quantum chest, but i can only request 64 coblestone ( i can't request more coblestone)
![2021-07-08_10 19 09](https://user-images.githubusercontent.com/50880693/124894744-37638400-dfdc-11eb-9b9a-9f6978dc0df8.png)
I think it only view this slot
![image](https://user-images.githubusercontent.com/50880693/124895166-9b864800-dfdc-11eb-8a1e-bbd5559b7b6f.png)

my game and mods version:
minecraft 1.12.2
forge 14.23.5.2855
IC2clasic 1.12-1.5.5.2.1
GT-Classic 1.1.6
logistics pipes 0.10.3.40

**Comment by e99999** [comment]
Not a bug, just really a lacking feature, there is no custom inventory handler to expose to the internal amount of cobblestone to the logistics system, same with AE2 or RS. I understand the desire for this to work however I have no plans to redo the tile at this point.
