### ISSUE TITLE
Things that should be done. (Todolist)

### ISSUE THREAD

**Issue by Speiger** [e99999/GT-Classic#34]
#### Localization References need to be streamlined.
- [x] Industrial Centrifuge
- [x] LargeChest
- [x] Super Condensator
- [x] Small Chest
- [x] Quantum Chest

#### Container Slots with missing filters need to be done.
- [x] Industrial Centrifuge
- [ ] Quantum Chest (Input Filter to make sure it can not clog up)

#### Misc stuff
- [x] Entries have to be found for this list.

Gets updated as i find stuff.

**Comment by e99999** [comment]
all fixed, quantum chest stuff now will be a completely different tile/idea with a whole new set of issues I am sure 😃
