### ISSUE TITLE
Some Recipes in the industrial Centrifuge don't use oredict.

### ISSUE THREAD

**Issue by Trinsdar** [e99999/GT-Classic#56]
- [x] clay dust to lithium, silicon, and aluminum recipe doesn't use dustClay oredict 
- [x] rubber wood to 8 carbon, 8 sticky resin, 6 plantballs and 4 methane recipe doesn't use logRubber oredict
- [x] ender eye dusts to 8 ender pearl dust and 8 blaze powder uses dustEndereye but tech reborn's dust is dustEnderEye
- [x] netherrack dust to gold nugget, redstone, 4 sulfur dust, and coal dusts doesn't use dustNetherrack oredict
- [x] obsidian dust to 2 iron dusts, 6 silicon, and 4 oxygen doesn't use dustObsidian oredict
- [ ] raw porkchop, raw beef, raw fish, raw chicken, raw mutton to methane could use listAllmeatraw oredict.
- [ ] cooked porkchop, steak, cooked fish, cooked chicken, cooked mutton to methane could use listAllmeatcooked oredict
- [ ] carrot, potato to methane could use listAllveggie oredict

For the last three those oredicts might only be available when pam's harvestcraft is loaded

**Comment by e99999** [comment]
thanks! the last three only exist with pams, so ill add it later but for now  its not "broken". besides if you make an entire cooked pams meal for methane - well you probably fucked up 😁

**Comment by DBotThePony** [comment]
![javaw_Twt9guWsV8](https://user-images.githubusercontent.com/6339511/83475666-fdf74580-a4b8-11ea-93b2-6e9cfd332a6f.png)
![javaw_d8XLi1Oimy](https://user-images.githubusercontent.com/6339511/83475670-ff287280-a4b8-11ea-8db2-d1b0aea0eeef.png)
![javaw_HptnwkMkk2](https://user-images.githubusercontent.com/6339511/83475671-ffc10900-a4b8-11ea-851f-24e304c0897e.png)
![javaw_mMBx6TldmU](https://user-images.githubusercontent.com/6339511/83475672-ffc10900-a4b8-11ea-8cb2-a0c0fb5e6d26.png)
![javaw_yHXky9HRWM](https://user-images.githubusercontent.com/6339511/83475674-00599f80-a4b9-11ea-8cc0-e215c760d3fe.png)
