### ISSUE TITLE
Ideas for Nuclear related stuff

### ISSUE THREAD

**Issue by e99999** [e99999/GT-Classic#71]
I have no idea about nuclear & reactor physics. please feel free to post any and all ideas you might want to see in GTC here

**Comment by kotelkonrad** [comment]
add fuels made in Actinide series

**Comment by e99999** [comment]
RTG stuff

**Comment by netmc** [comment]
A Pebble bed reactor is supposed to be one of the safest ones to run.

**Comment by kotelkonrad** [comment]
more enriched fuel rods

**Comment by kotelkonrad** [comment]
enriched thorium fuel rods

**Comment by kotelkonrad** [comment]
centrifuging depleted enriched fuels receives for example : plutonium infused ender pearl, plutonium infused redstone, plutonium infused charcoal, plutonium infused blaze rod, plutonium infused nether star

**Comment by Avinex68** [comment]
Fission fuel processing chains that would make items used in fusion reactions

**Comment by kotelkonrad** [comment]
add tier 2 steam or normal nuclear reactor , add nuclear chamber extension
add 2d texture to fuel rods 
placeable uranium rods and enriched versions

**Comment by Erik3003** [comment]
A reactor steam pipe. A pseudo-fluid pipe that can just pump steam, but unlimited amounts. Only accepts input directly from reactors (and maybe Railcraft boilers if going the compat route) and outputs into any other connections (that are not reactors).  Would make IC2C steam reactors actually usable.
