### ISSUE TITLE
Just Speiger Things

### ISSUE THREAD

**Issue by e99999** [e99999/GT-Classic#76]
Important:

- [x] GTTileBlockCustom.getDrops() //Needs a fix with copies.
- [x] Local Components need to be made static finally.
- [x] InputSlotFilters in MultiInput Machines have to be done properly
- [x] Int3 needs a Mutable BlockPos integrated.
- [x] Export Loops should not move 1 item at the time for 64 times. It should do as many items as - [ ] possible (attempt to move 64 items at once instead)
- [x] Many TileEntities can set its facing no matter what and only can be harvested if you wrench it from top or bottom.
- [x] TileFacing needs a rewrite.
- [x] Import & Exporting Tiles can load chunks and can technically cause chunk cascading. Like hoppers can do.
- [x] Other MultiBlocks still need their Energy & UI Opener implemented
- [x] Interrupt power message gui component because users are stupid
Less Important:
- [x] LocalComp should be implemented properly. (Not hard work)
- [x] Localization needs to be finished. Some Gui Classes miss them
- [x] All un implemeneted things should be not visible at all. (Things that may come or not)
- [x] Teleport Command should be disabled so its not allowing cheats

**Comment by Speiger** [comment]
Int3 uses Mutable BlockPos now.

**Comment by e99999** [comment]
all done 🐶
