### ISSUE TITLE
Tiny Code improvements.

### ISSUE THREAD

**Issue by Speiger** [e99999/GT-Classic#8]
https://github.com/e99999/GT-Classic/blob/master/src/main/java/gtclassic/blocks/resources/GTBlockOre.java#L60
Could be moved into the Enum Instead since its not a "Dynamic Drop".

https://github.com/e99999/GT-Classic/blob/master/src/main/java/gtclassic/blocks/machines/lv/GTBlockAlloySmelter.java#L16
Should extends BlockMultiID because extending the current class might break things if i change stuff in the core.

https://github.com/e99999/GT-Classic/blob/master/src/main/java/gtclassic/items/tools/GTItemAdvancedChainsaw.java#L43
That thing wont work because it is a reference to the AudioManagerClient (line 504) which is adding a tracker for entities that could have chainsaws in their hand. You need to write a tracker for there to play the audiosource track. 

I hope thats some information how to improve things ^^"

**Comment by Speiger** [comment]
https://github.com/e99999/GT-Classic/blob/master/src/main/java/gtclassic/items/tools/GTItemMortarFlint.java#L33
Tiny Improvement here that makes the logic much safer.
```java
    @Override
    public ItemStack getContainerItem(ItemStack itemStack)
    {
	ItemStack copy = itemStack.copy();
	return copy.attemptDamageItem(1, itemRand, null) ? ItemStack.EMPTY : copy;
    }
```

**Comment by Speiger** [comment]
https://github.com/e99999/GT-Classic/blob/master/src/main/java/gtclassic/GTClassicTextureLoaderHelper.java#L9

No longer needed there is now a Event for that in IC2Icons if you look it up thats now useable.

**Comment by Speiger** [comment]
https://github.com/e99999/GT-Classic/blob/master/src/main/java/gtclassic/world/GTOreGen.java#L85
Look up in worldgen mineable how its "default" predicate is because ores can also generate in none "Stone" blocks that are still "StoneTypes"

**Comment by Speiger** [comment]
https://github.com/e99999/GT-Classic/blob/master/src/main/java/gtclassic/tileentity/GTTileEntitySmallBuffer.java#L20
SideOnly(Side.Client) missing. Willl crash servers otherwise.

**Comment by Speiger** [comment]
https://github.com/e99999/GT-Classic/blob/master/src/main/java/gtclassic/container/GTContainerSmallBuffer.java#L16
If the filter is null then just use SlotBase

**Comment by e99999** [comment]
all fixed
