### ISSUE TITLE
LESU should use the new Search logic.

### ISSUE THREAD

**Issue by Speiger** [e99999/GT-Classic#89]
https://github.com/e99999/GT-Classic/blob/master/src/main/java/gtclassic/tile/GTTileLESU.java#L94
Should include the maximum radius. Or a decent size radius. Because if it is only 3 blocks then you have at best a 32x32 area and at worst 16x16 area loaded.

https://github.com/e99999/GT-Classic/blob/master/src/main/java/gtclassic/tile/GTTileLESU.java#L113
Use the Progress variant because logic may cause lag if people ignore the 256 limit.

**Comment by e99999** [comment]
fixed
